name: sub_zipper_fr
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  archive: ^3.1.11
  dcli: ^1.16.2
  random_string: ^2.3.1
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
